feat: добавлены методы для работы с событиями
mesto-co/core pull request #128
Opened 2021-01-13 17:08 UTC by ak239

/v1/event/addEvent добавляет событие, доступно лишь пользователям
с разрешением Permission.EVENT
/v1/event/editEvent редактирует события, доступно пользователям с
Permission.EVENT и автором события,
/v1/event/joinEvent добавляет текущего пользователя в список идущих
/v1/event/unjoinEvent удаляет текущего пользователя из идущих
в api.json описаны все доступные параметры методов.

2021-01-13 17:53 UTC, skuznetsov requested changes

2021-01-13 17:53 UTC, skuznetsov commented on migrations/20210111184458_event.js
> +  await knex.raw(`INSERT INTO permission(id, description) VALUES (4, 'Allow to ban user')`);
Тут у тебя несоответствие текста кодам в Permission enum (там 2 - activate, 3 - ban, etc). И из-за этого сдвиг.
Потеряшка - SENDINVITEEMAIL = 5,
Перепроверь пожалуйста.

2021-01-13 17:53 UTC, skuznetsov commented on migrations/20210111184458_event.js
> +        event_id uuid references event(id)
Хорошо бы два индекса сюда. Один на эвент, второй на юзера.

2021-01-13 17:58 UTC, ak239 commented on migrations/20210111184458_event.js
> +  await knex.raw(`INSERT INTO permission(id, description) VALUES (4, 'Allow to ban user')`);
fixed

2021-01-13 17:58 UTC, ak239 commented on migrations/20210111184458_event.js
> +        event_id uuid references event(id)
added

2021-01-13 18:01 UTC, skuznetsov commented on src/schema/api.json
> +        "title": { "type": "string", "maxLength": 128 },
Хорошо бы и минимумы тут указать.

2021-01-13 18:04 UTC, ak239 commented on src/controllers/eventController.ts
> +    if (e.code === '23503')
FOREIGN KEY VIOLATION в данном случае значит что либо события такого нет, либо пользователя

2021-01-13 18:05 UTC, skuznetsov commented on src/controllers/eventController.ts
> +    if (e.code === '23503')
Понял, тогда игнорируй ;)

2021-01-18 23:22 UTC, ak239 commented on src/controllers/eventController.ts
> +      return response.status(400).json({}).end();
done!

2021-01-18 23:22 UTC, ak239 commented on src/controllers/eventController.ts
> +    await knex.raw('DELETE FROM event_user WHERE event_id = :id', { id });
done!

2021-01-18 23:24 UTC, ak239 commented on src/schema/api.json
> +        "title": { "type": "string", "maxLength": 128 },
done.

2021-01-19 00:49 UTC, skuznetsov requested changes

2021-01-19 00:49 UTC, skuznetsov commented on src/controllers/eventController.ts
> +    const {rowCount} = await knex.raw('UPDATE event SET title = :title, description = :description, image = :image, link = :link, time = :time WHERE id = :id AND creator = :currentUser', {
Я думаю что тут есть вариант изменения удаленного события если известен его ID. проверку на status = CREATED было бы здорово.

2021-01-19 00:49 UTC, skuznetsov commented on src/controllers/eventController.ts
> +    await knex.raw('DELETE FROM event_user WHERE user_id = :userId AND event_id = :id', {
Я бы добавил тут такой же статус как и у эвента. И если он опять присоединился, то просто поменять статус.
Может пригодиться для возможных расследований. Хотя тут я не настаиваю, можно и потом, если вдруг возникнет нестандартная ситуация на предмет зарегался ли кто-то на этот эвент, потом нашкодил, и отсоединился после эвента. 

Хорошо бы еще сделать запрет на unjoin если событие уже прошло.

2021-01-25 01:48 UTC, ak239 commented on src/controllers/eventController.ts
> +    const {rowCount} = await knex.raw('UPDATE event SET title = :title, description = :description, image = :image, link = :link, time = :time WHERE id = :id AND creator = :currentUser', {
done.

2021-01-25 01:49 UTC, ak239 commented on src/controllers/eventController.ts
> +    await knex.raw('DELETE FROM event_user WHERE user_id = :userId AND event_id = :id', {
предлагаю все это сделать потом, мне непонятно, что значит unjoin если событие уже прошло, либо join на такое событие - посмотрим как люди будут пользоваться и сделаем что-нибудь.

2021-01-25 11:29 UTC, skuznetsov approved these changes

2021-01-25 16:33 UTC, merged