edit query for joined users
mesto-co/core pull request #146
Opened 2021-06-08 10:41 UTC by daitkhealex

2021-06-08 15:58 UTC, ak239 commented on src/controllers/eventController.ts
> +    const {rows}: {rows: [{id: string, fullName: string, imagePath: (string|null), event_id: string}]} = await knex.raw(`select "User".id, "User"."fullName", "User"."imagePath", event_user.event_id f
тест?

2021-06-08 16:00 UTC, ak239 requested changes
нужен тест и, пожалуйста, более подробное описание комита, что-то в духе
fix(event): getJoinedUsers должен возвращать event_id

2021-06-15 17:32 UTC, ak239 requested changes

2021-06-15 17:32 UTC, ak239 commented on src/controllers/eventController.ts
> +    const caseWhenClause = ` case when exists (select true from event_user where user_id= :user AND event_id=eu.event_id) then 'true' else 'false' end as is_joined`;
мы делаем inner join либо left join с event_user табличкой в строчке 209 и 211, поэтому если eu.user_id либо eu.event_id не null, то user заджоинил, иначе нет, дополнительный запрос на каждого пользователя тут не обязателен.

2021-06-15 17:32 UTC, ak239 commented on src/controllers/eventController.ts
> +    const caseWhenClause = ` case when exists (select true from event_user where user_id= :user AND event_id=eu.event_id) then 'true' else 'false' end as is_joined`;
select eu.even_id is not null as is_joined

2021-06-15 17:32 UTC, ak239 commented on test/v1/eventController.spec.js
> +  const eventData = {
если нужно переформатировать файл - это лучше всегда делать отдельным PR, иначе сложно найти изменения, которые непосредственно относятся к текущему PR.

2021-06-15 17:32 UTC, ak239 commented on test/v1/eventController.spec.js
> +  expect(await getJoinedUsers(null)).toMatchObject({code: 400});
Можешь, пожалуйста, указать, где именно происходит проверка того, что getJoinedUsers возвращает event_id, не вижу такого теста.

2021-06-15 17:32 UTC, ak239 commented on src/controllers/eventController.ts
> +    const result = rows.map((row: { id: string; creator: string; time: string; time_end: string; category: string; title: string; description: string; image: string; user_id: string|undefined; link:
Если мы хотим в этом PR еще и search поправить, то для него тоже нужен тест.

2021-06-15 17:36 UTC, daitkhealex commented on src/controllers/eventController.ts
> +    const caseWhenClause = ` case when exists (select true from event_user where user_id= :user AND event_id=eu.event_id) then 'true' else 'false' end as is_joined`;
Фронту нужно знать в списке текущий пользователь, который список просматривает заджоин в мероприятии или нет. для этого пришлось делать этот запрос дополнительно

2021-06-15 17:39 UTC, daitkhealex commented on src/controllers/eventController.ts
> +    const caseWhenClause = ` case when exists (select true from event_user where user_id= :user AND event_id=eu.event_id) then 'true' else 'false' end as is_joined`;
Для каждой карточки списка событий есть кнопка "я иду" и она должна переключаться на "я пойду". Для этого в списке нужно всегда знать идет или нет пользователь

2021-07-01 16:52 UTC, ak239 commented on src/controllers/eventController.ts
> +    const {rows}: {rows: [{id: string, fullName: string, imagePath: (string|null)}]} = await knex.raw(`select "User".id, "User"."fullName", "User"."imagePath", event_user.event_id from "User" inner j
мы достаем event_id, но не используем его, это запланировано?

2021-07-01 16:54 UTC, ak239 commented on src/controllers/eventController.ts
> +    const result = rows.map((row: { id: string; creator: string; time: string; time_end: string; category: string; title: string; description: string; image: string; user_id: string|undefined; link:
нужен тест, который бы проверял, что мы возвращаем правильное значение для is_joined.

2021-07-01 16:55 UTC, daitkhealex commented on src/controllers/eventController.ts
> +    const {rows}: {rows: [{id: string, fullName: string, imagePath: (string|null)}]} = await knex.raw(`select "User".id, "User"."fullName", "User"."imagePath", event_user.event_id from "User" inner j
Все верно, это функция контроллера для получения всех заджойненных пользователей. При этом на фронтенде знают всегда event_id, к которому обратились

2021-07-01 16:57 UTC, ak239 commented on src/controllers/eventController.ts
> +    const {rows}: {rows: [{id: string, fullName: string, imagePath: (string|null)}]} = await knex.raw(`select "User".id, "User"."fullName", "User"."imagePath", event_user.event_id from "User" inner j
предлагаю не доставать его.

2021-07-01 16:59 UTC, daitkhealex commented on src/controllers/eventController.ts
> +    const {rows}: {rows: [{id: string, fullName: string, imagePath: (string|null)}]} = await knex.raw(`select "User".id, "User"."fullName", "User"."imagePath", event_user.event_id from "User" inner j
так и сделаю, уберу из запроса

2021-07-02 16:16 UTC, ak239 approved these changes

2021-07-02 16:16 UTC, merged