feat: find profiles volume 2
mesto-co/core pull request #44
Opened 2020-09-18 17:11 UTC by skobak

По #23 улучшение
- Улучшил поиск пользоватлей по нескольким словам в запросе
- Добавил CORS, чтобы не ругался при тестирование API с frontend
- Добавил User Seed генерацию людей при помощи faker библиотеки (оставил первого юзера не тронутым если на него есть тесты)

2020-09-18 17:59 UTC, ak239 requested changes

2020-09-18 17:59 UTC, ak239 commented on CONTRIBUTING.md
> +- Проверить пакет на его размер на https://bundlephobia.com/ и посмотреть альтрнативы
я точно помню, что мы мержили эту строчку - ребейзни, пожалуйста, на мастер

2020-09-18 17:59 UTC, ak239 commented on package.json
> +    "start:in-docker:ci": "node utils/wait-for.js postgres 5432 50000 && npm run build && knex migrate:latest &&  knex seed:run && node ."
эта строчка тоже была

2020-09-18 17:59 UTC, ak239 commented on seeds/01_users.js
> +userCount = 100;
const userCount

2020-09-18 17:59 UTC, ak239 commented on src/controllers/profileController.ts
> +      const queryArr: String[] = query.split(' ');
как минимум разбивать строку на подстроки может фронтенд - метод может принимать сразу массив.
клиентов много - сервер с API один, больше работы там - меньше счет за AWS.
и в целом генерить все возможные комбинации из полей тоже можно на фронтенде:
```
[{firstName:string, lastName:string,middleName:string,username: string,location:string, about:string, role:string}, ...]
```
пусть метод принимает хотя бы что-то такое - массив объектов, с полями для фильтрации со значениями, а фронтенд их нагенерит уже, что-то в духе:
```
const query = fullQuery.split(' ');
const request = [];
for (const queryItem of query) {
  request.push({firstName: queryItem}, {lastName: queryItem}, {middleName: queryItem}, ...);
}
fetch(api, {query: request, RqUid, currentPage);
```

у нас тогда будет значтельно более гибкий API, который сразу заработает когда мы сделаем поиск по отдельным полям.

2020-09-18 17:59 UTC, ak239 commented on src/controllers/profileController.ts
> +      const entries = await UserEntries().select().where((builder: Knex.QueryBuilder) => {
limit бы еще в параметрах передавать. у нас еще с пагинацией фундаментальная проблема, что если кто-то во время запросов добавит новую запись, то одна и та же запись вернется несколько раз - нужно сортировать по времени добавления в таблицу.

2020-09-20 12:09 UTC, skobak commented on CONTRIBUTING.md
> +- Проверить пакет на его размер на https://bundlephobia.com/ и посмотреть альтрнативы
ок, вроде делал rebase , но видимо что то наломал с гитом

2020-09-21 13:51 UTC, icekhab approved these changes

2020-09-21 18:47 UTC, ak239 commented on src/schema/api.json
> +                            "type" : "string"
пожалуйста, добавь везде maxLength, в соотвествии с описанием полей в БД, чтобы немного снизить вероятность ddos.

2020-09-21 18:49 UTC, ak239 approved these changes
maxLength к полям и можно мержить!

2020-09-21 20:33 UTC, icekhab commented on src/controllers/profileController.ts
> +      }).where({status: 'approved'}).orderBy('createdAt','asc').paginate({ perPage, currentPage });
{status: 'approved'} -> {status: UserStatus.APPROVED}

2020-09-22 09:59 UTC, merged