feat: добавлен рут для локаций и сохранения данных пользователя
mesto-co/core pull request #50
Opened 2020-09-23 09:23 UTC by TyroniUA

LocationsController использует три таблицы. На данный момент они устанавливаются мануально из script.sql файла в папке миграций. 

Отлимитировал поиск по первому объекту в массиве для уменьшения нагрузки на сервер.
Жду решения от Алексея по поводу автоматической миграции.

SaveUserDetailsController апдейтит данные пользователя: about, contacts (поле ссылки согласно дизайну) и location.

Работа для #21 #22

2020-09-23 17:16 UTC, ak239 commented on src/controllers/saveUserDetailsController.ts
> +router.route('/').post(async (request, response) => {
кажется, что этот метод обновляет поля, а не создает запись - PUT.

2020-09-23 17:18 UTC, ak239 commented on src/controllers/saveUserDetailsController.ts
> +    await UserTable().where('id', id).update({
если пользователь не найден, то будет здорово вернуть 404, либо 409.

2020-09-23 17:20 UTC, ak239 commented on src/schema/api.json
> +            "userInput": { "type": "object" }
тут нужно перчислить все поля, которые могут быть в этом объекте, и мне кажется можно обойтись без вложенного объекта userInput - просто все перечислить в properties.

2020-09-23 17:24 UTC, ak239 commented on src/controllers/locationController.ts
> +      const location = await CityTable().where('name', 'like', `%${userInput}%`);
leftJoin сэкономит запросы к базе данных.
``` 
       await knex
        .select(
            'u.id',
            'u.first_name',
            'u.last_name',
            'u.username',
            'u.image_url',
            'u.is_admin',
            'u.phone',
            'u.info',
            'la.email',
            'cu.customer_id',
            'cu.department_id'
        )
        .from('city AS c')
        .leftJoin('region AS r', 'r.id', 'c.region_id')
        .leftJoin('country AS co', 'r.country_id', 'co.id')
        .where('name', 'ilike', `%{userInput}%`)
        .first()
```

2020-09-23 17:26 UTC, ak239 commented on test/v1/location/locationController.spec.js
> +  const userInput = 'Ки';
в будущем нам нужно добавить условное население городов и сортировать результаты по нему - я больше поверю, что Ки это Киев, чем Кикерино :)

2020-09-24 09:01 UTC, TyroniUA commented on src/controllers/saveUserDetailsController.ts
> +    await UserTable().where('id', id).update({
Думал над этим, но возник вопрос. Если пользователь с фронта отправляет запрос на обновление - то он автоматически вошел в систему и получил айди. Этот айди он и перенаправляет. Как тогда он может быть не найден, если согласно таблицы он только что вошел и получил айди?

2020-09-24 09:01 UTC, TyroniUA commented on src/controllers/saveUserDetailsController.ts
> +router.route('/').post(async (request, response) => {
Исправлю

2020-09-24 16:42 UTC, skuznetsov requested changes

2020-09-24 16:42 UTC, skuznetsov commented on src/controllers/saveUserDetailsController.ts
> +    await UserTable().where('id', id).update({
Есть вариант что кто-то еще зарегистрированный хочет модифицировать данные другого. Мы должны убедиться что id залогиненного пользователя совпадает с ID пользователя. Лучше вообще не использовать поле ID, а брать его с настроек залогиненного пользователя.

2020-09-24 17:36 UTC, ak239 commented on src/controllers/saveUserDetailsController.ts
> +    await UserTable().where('id', id).update({
мы там замержили Женин PR с авторизацией, все ендпоинты которые после авторизации нынче получают request.user.userId. как заметил Сергей - этот метод должен использовать userId оттуда, а не из параметров - пользователь должен иметь возможность редактировать только себя.

2020-09-28 06:57 UTC, icekhab commented on migrations/20200913141937_create_user_table.js
> +    table.string('contacts').nullable();
Есть таблица Contact, нужно убрать отсюда поле и сохранять Array объектов контактов в эту таблицу

2020-09-28 06:57 UTC, icekhab commented on src/schema/api.json
> +                    "properties": {
Тут поля должны быть title и url

2020-09-28 06:57 UTC, icekhab commented on src/controllers/saveUserDetailsController.ts
> +        about: about || '',
стоит прописать "required" в схеме валидации и убрать `|| ''` отсюда

2020-09-28 16:49 UTC, ak239 commented on src/controllers/locationController.ts
> +        const city = await knex.select('name').from('City').where('name','like',`%${userInput}%`).first();
```
const country = await knex.select('c.name as countryName','co.name as cityName')
            .from('City AS c')
            .leftJoin('Region AS r', 'r.id', 'c.region_id')
            .leftJoin('Country AS co', 'r.country_id', 'co.id')
            .where('c.name', 'ilike', `%Моск%`)
            .first();
```

2020-09-29 05:50 UTC, TyroniUA commented on src/controllers/locationController.ts
> +        const city = await knex.select('name').from('City').where('name','like',`%${userInput}%`).first();
Да, согласен. Чистый пулл был и забыл заново прописать твой фикс.

2020-09-29 17:21 UTC, ak239 commented on src/controllers/locationController.ts
> +        response.status(200).json({ location, RqUid }).end();
будет здорово явно перечислить поля, которые мы возвращаем:
```
{ location: { cityName: location.cityName, countryName: location.contryName }, RqUid }
```
чтобы ничего лишнего не утекло.

2020-09-29 17:24 UTC, ak239 commented on src/controllers/saveUserDetailsController.ts
> +      const newContacts = contacts.map((e: any) => ({
кажется, что мы не можем обновить существующие контакты, только добавить новые?
предлагаю разнести на две части. одна про контакты - где методы post - добавить, put - обновить контакт, и delete - удалить контакт. другая про пользователей.

2020-09-29 17:25 UTC, ak239 commented on src/schema/api.json
> +                        "id": { "type": "number"},
этот id тут указан, но кажется, что мы его не используем. отдельный endpoint для контактов все упростит.

2020-09-30 09:44 UTC, ak239 commented on src/schema/api.json
> +            "role":{"type": "string"},
maxLength

2020-09-30 09:44 UTC, ak239 commented on src/app.ts
> +register(app, '/v1/profile/info/', SaveUserDetailsController, true);
Будет здорово повесить это на /v1/user мне кажется там put метод ещё свободен.

2020-09-30 09:44 UTC, ak239 commented on src/schema/api.json
> +            "userInput": { "type": "string" }
maxLength

2020-09-30 09:44 UTC, ak239 commented on test/v1/profile/saveUserDetailsController.spec.js
> +  const skills = [1, 2, 3];
Ещё бы тест на валидные skills

2020-09-30 20:00 UTC, ak239 commented on src/controllers/saveUserDetailsController.ts
> +// /**
этот файл к сожалению необходимо уничтожить

2020-09-30 20:04 UTC, ak239 approved these changes
спасибо!

2020-09-30 20:17 UTC, skuznetsov approved these changes

2020-09-30 20:17 UTC, icekhab approved these changes

2020-09-30 20:19 UTC, ak239 commented
я замержу - на всякий случай, чтобы больше никто не пытался прямо сейчас :)

2020-09-30 20:34 UTC, merged